#!/bin/bash

TERMINAL="$HOME/.i3/termite_wrap"
"$HOME"/.i3/init_ws -l "$HOME/.i3/music_ws.json" \
	-c "$TERMINAL -t cmus -e cmus" \
	-c "$TERMINAL -t Terminal"

$TERMINAL -t alsamixer -e "alsamixer -g -c 0 -V -all"
