#!/bin/bash
# Tiny bash script to launch pseudo-aleatory color schemes termite terminals
#

# for debuging
#trap 'set +x; sleep 1; set -x' DEBUG

_TERMITE="$(command -v termite)"
_configdir="$HOME"/.config
_termitedir="$_configdir"/termite
declare -a _conf_files
declare -a _COMMANDLINE

# main script
#
_conf_files=( $(ls "$_termitedir"/*.config) )
# generate pseudo-random num lower than _conf_files size
RANDOM=$(head -1 /dev/urandom | od -N 1 | awk '{ print $2 }')
_rand=$(( RANDOM %= ${#_conf_files[@]} ))

# check for file readability and launch termite or notify an error
if [ -r "${_conf_files[$_rand]}" ]; then
	_COMMANDLINE=( "-c" "${_conf_files[$_rand]}" )
else
	notify-send -u critical "termite_wrap failed" "${_conf_files[$_rand]}\nDo not exist or is not user readable. _rand index is $_rand (it should be in range 0 - $(( ${#_conf_files[@]}-1 )))"
	exit 1
fi
# add the rest of the command line options
_COMMANDLINE+=( "$@" )

# launch the command
"$_TERMITE" "${_COMMANDLINE[@]}" &
