#!/bin/bash
# Tiny bash script to launch pseudo-aleatory color schemes alacritty terminals
#

# for debuging
#trap 'set +x; sleep 1; set -x' DEBUG

_ALACRITTY="$(command -v alacritty)"
_configdir="$HOME"/.config
_alacrittydir="$_configdir"/alacritty
declare -a _conf_files
declare -a _COMMANDLINE

# main script
#
_conf_files=( $(ls "$_alacrittydir"/alacritty*.toml) )
# generate pseudo-random num lower than _conf_files size
RANDOM=$(head -1 /dev/urandom | od -N 1 | awk '{ print $2 }')
_rand=$(( RANDOM %= ${#_conf_files[@]} ))

# check for file readability and launch alacritty or notify an error
if [ -r "${_conf_files[$_rand]}" ]; then
	_COMMANDLINE=( "--config-file" "${_conf_files[$_rand]}" )
else
	notify-send -u critical "alacritty_wrap failed" "${_conf_files[$_rand]}\nDo not exist or is not user readable. _rand index is $_rand (it should be in range 0 - $(( ${#_conf_files[@]}-1 )))"
	exit 1
fi
# add the rest of the command line options
_COMMANDLINE+=( "$@" )

# launch the command
"$_ALACRITTY" "${_COMMANDLINE[@]}" &
