#!/usr/bin/env sh
set -x
report_msg()
{
	printf "**** %s\t%s\n" "$1" "$2"
}

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
	_display_line="WAYLAND_DISPLAY=$WAYLAND_DISPLAY"
	_run_line=/run/user/"$(id -u)"/"$WAYLAND_DISPLAY":/run/user/"$(id -u)"/"$WAYLAND_DISPLAY"
	_other="--enable-features=UseOzonePlatform --ozone-platform=wayland"
else
	_display_line="DISPLAY=$DISPLAY"
	_run_line="$HOME/.Xauthority:/home/boret/.Xauthority"
	_other=""
fi
# Are we running dockerd service?
if ! pgrep -c dockerd >/dev/null 2>&1; then
	report_msg "docker service not running." "Starting ..."
	sudo systemctl start docker
fi

_DOCKER="$(command -v docker)"

report_msg "${0##*\/}" "Starting Arduino IDE ..."
"$_DOCKER" run \
	--name arduino_ide \
	-i \
	--rm \
	--network=host \
	--privileged \
	-e "$_display_line" \
	-e ELECTRON_OZONE_PLATFORM_HINT=auto \
	-e XDG_RUNTIME_DIR=/run/user/"$(id -u)" \
	-v /dev:/dev \
	-v "$_run_line" \
	-v "$HOME"/Arduino:/home/boret/Arduino \
	-v "$HOME"/.arduino15:/home/boret/.arduino15 \
	boret/amd64:arduino_ide-2-3-0 \
	arduino-ide "$_other" >/dev/null 2>&1 &
sleep 5
report_msg "${0##*\/}" "Enjoy ..."

