#!/bin/bash
#vim "+vert terminal" "+terminal ++rows=28 arduino_cli" "$@"

i3-msg "append_layout $HOME/.i3/arduino_layout.json"
alacritty --config-file "$HOME/.config/alacritty/alacritty_boret_deep_blue.yml" -e arduino_cli &
sleep 0.25
alacritty --config-file "$HOME/.config/alacritty/alacritty_boret_deep_blue.yml" &
sleep 0.25
alacritty --config-file "$HOME/.config/alacritty/alacritty_boret_deep_blue.yml" -e vim "$@" &
