udisks_version: 0
tray:           true
automount:      true
notify:         true
file_manager:   thunar
mount_options:
#        - id_type:      vfat
#        - id_uuid:      E3FC-8328
        - device_file:  /dev/sda6
          options:      [rw, users, async]
notifications:
        timeout:                1.5
        device_mounted:         5
        device_unmounted:       false
        device_added:           -1
        device_removed:         -1
notification_actions:
        device_mounted:         [browse]
        device_added:           [mount]
