general.import = ["/home/boret/.config/alacritty/common.toml"]

[colors.bright]
black = "#10151b"
blue = "#093748"
cyan = "#599caa"
green = "#081f2d"
magenta = "#888ba5"
red = "#d26939"
white = "#d3ebe9"
yellow = "#245361"

[colors.cursor]
cursor = "#98d1ce"
text = "CellBackground"

[colors.normal]
black = "#0a0f14"
blue = "#195465"
cyan = "#33859d"
green = "#26a98b"
magenta = "#4e5165"
red = "#c33027"
white = "#98d1ce"
yellow = "#edb54b"

[colors.primary]
background = "#0a0f14"
foreground = "#98d1ce"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[font]
size = 10.0

[font.bold]
family = "Ubuntu Mono derivative Powerline"
style = "Bold"

[font.bold_italic]
family = "Ubuntu Mono derivative Powerline"
style = "Bold Italic"

[font.italic]
family = "Ubuntu Mono derivative Powerline"
style = "Italic"

[font.normal]
family = "Ubuntu Mono derivative Powerline"
style = "Medium"
