general.import = ["/home/boret/.config/alacritty/common.toml"]

[colors.bright]
black = "#5f5f5f"
blue = "#4a7781"
cyan = "#4bb5c1"
green = "#a6cd07"
magenta = "#ff3b77"
red = "#ff3a78"
white = "#e2e2e5"
yellow = "#b5c865"

[colors.cursor]
cursor = "#ffffff"
text = "CellBackground"

[colors.normal]
black = "#303030"
blue = "#426870"
cyan = "#4bb5c1"
green = "#b1d631"
magenta = "#6d506d"
red = "#c03000"
white = "#e2e2e5"
yellow = "#fecf35"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[font]
size = 8.0

[font.bold]
family = "Monospace"
style = "Bold"

[font.bold_italic]
family = "Monospace"
style = "Bold Italic"

[font.italic]
family = "Monospace"
style = "Italic"

[font.normal]
family = "Monospace"
style = "Medium"
