[cursor]
blink_interval = 550
thickness = 0.05
unfocused_hollow = true
vi_mode_style = "None"

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
title = "Terminal"

[window.class]
general = "Alacritty"
instance = "alacritty"

#[keyboard]
#bindings = [
  #{key = "PageUp", mods = "Control", action = "None"},
  #{key = "PageDown", mods = "Control", action = "None"}
#]
