#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

#------------------------------------------------------------------------
# Variation on i3blocks' bandwidth script to fit our own lemonbar
# status bar.
# Boret  04/2018
#------------------------------------------------------------------------
use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $full_text;
my $short_text;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;
my $color;

while (1) {
	# read the first line of the "acpi" command output
	open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
	$acpi = <ACPI>;
	close(ACPI);

	# fail on unexpected output
	if ($acpi !~ /: (\w+), (\d+)%/) {
		die "$acpi\n";
	}

	$status = $1;
	$percent = $2;
	$full_text = "$percent%";

	# Icons and text color definition. Color only while discharging
	if ($status eq 'Charging') {
		$full_text .= ' ';
		$color = "#5e745d\n";
	} elsif ($status eq 'Discharging') {

		if ($percent < 20 && $percent >= 5) {
			$color = "#5c2203\n";
			$full_text .= ' ';
		} elsif ($percent < 40 && $percent >= 20) {
			$color = "#5b5c03\n";
			$full_text .= ' ';
		} elsif ($percent < 60 && $percent >= 40) {
			$color = "#03385c\n";
			$full_text .= ' ';
		} elsif ($percent < 100 && $percent >= 60) {
			$color = "#07035c\n";
			$full_text .= ' ';
		# Modificado, en lugar de abortar, envía notificación al sistema
		} elsif ($percent < 5) {
			$full_text .= ' ';
			$color = "#5c0303\n";
			system "/usr/bin/notify-send --urgency=critical 'BATERIA BAJA' 'Batería inferior al 5%. Conecta el cargador urgentemente'";
		# Shutdown con la batería al 2% para evitar cierres bruscos
		} elsif ($percent < 2) {
			system "sudo shutdown -h now";
		}
	} else {
		$full_text .= ' ';
		$color = "#5e745d\n";
	}

	if ($acpi =~ /(\d\d:\d\d):/) {
		$full_text .= " ($1)";
	}

	# print text
	print "BAT$full_text $color";
	sleep 60
}
exit(0);
