#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
# Variation on i3blocks' iface script to fit our own lemonbar
# status bar.
# Boret  04/2018
#------------------------------------------------------------------------

#for debugging
#_sleep="$(which sleep)"
#trap 'set +x; $_sleep 0.50; set -x' DEBUG

# Use the provided interface, otherwise the device used for the default route.
IF=$(ip route | awk '/^default/ { print $5 ; exit }')

# if there's no ifce, try to find one UP except loopback
if [[ ! -n $IF ]] || [[ $IF == 'link' ]]; then
	IF=`ip link |grep "state UP" |grep -v LOOPB |awk -F": " '{print $2}'`
fi

# Without connection the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${IF} ]] && exit

case $1 in
  -4)
    AF=inet ;;
  -6)
    AF=inet6 ;;
  *)
    AF=inet6? ;;
esac

# if no interface is found, use the first device with a global scope
IPADDR=$(ip addr show $IF | perl -n -e "/$AF ([^\/]+).* scope global/ && print \$1 and exit")

# Print something only if we have an ip address
[[ -n "$IPADDR" ]] && echo "IFC$IPADDR"
