#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Boret: If BLOCK_INSTANCE is not set get default route link
#------------------------------------------------------------------------

INTERFACE="${BLOCK_INSTANCE:-$(ip route | grep default| grep -v linkdown |cut -d" " -f5)}"

# Boret: Get access point ESSID
#------------------------------------------------------------------------
APOINT=`2>/dev/null iwconfig |grep ESSID |cut -d":" -f2 |sed s/\"//g |sed s/off.*$//`

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

#------------------------------------------------------------------------

echo $APOINT" "$QUALITY% # full text
echo $APOINT" "$QUALITY% # short text

# color
if [[ $QUALITY -ge 80 ]]; then
    echo "#006e34"
elif [[ $QUALITY -lt 80 && $QUALITY -ge 60 ]]; then
    echo "#716d00"
elif [[ $QUALITY -lt 60 && $QUALITY -ge 40 ]]; then
    echo "#734f00"
elif [[ $QUALITY -lt 40 ]]; then
    echo "#720000"
fi

case $BLOCK_BUTTON in
    3) /usr/bin/cool-retro-term -e wicd-curses ;;
esac
